# Generated by Django 5.2 on 2025-05-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='C:/Users/eshap/Documents/Cybersecurity/Year 2/PLCS labs/oop.png', null=True, upload_to='profile_pic/CustomerProfilePic/'),
        ),
    ]
