name: CI Pipeline with Snyk and ZAP for Render

on:
  push:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Snyk scan
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

  zap-dast:
    needs: security-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Wait for Render app to deploy
        run: sleep 90

      - name: Create output folder
        run: mkdir -p zap-output

      - name: Pull ZAP container
        run: docker pull ghcr.io/zaproxy/zaproxy:stable

      - name: Run OWASP ZAP full scan
        continue-on-error: true
        run: |
          docker run --rm --user root \
            -v ${{ github.workspace }}/zap-output:/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py \
            -t https://securecart-website2.onrender.com \
            -J report_json.json -w report_md.md -r report_html.html

      - name: Upload ZAP scan results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zapscanreport
          path: |
            zap-output/report_json.json
            zap-output/report_md.md
            zap-output/report_html.html
